---
- hosts: solace
  connection: local
  gather_facts: no
  tasks:
    - name: Gather EC2 remote facts.
      ec2_instance_facts:
        region: "{{ region | default('ap-southeast-1') }}"
        filters:
          ip-address: "{{ inventory_hostname }}"
      register: ec2_instance_facts
    - name: Debug.
      debug:
        var: ec2_instance_facts.instances[0].instance_id

    - name: terminating single instance
      local_action:
        module: ec2
        state: 'absent'
        region: ap-southeast-1
        instance_ids: "{{ item.instance_id }}"
      with_items: "{{ ec2_instance_facts.instances }}"

    - name: remove the host entry from the inventory
      lineinfile:
        dest: "hosts"
        regexp: "{{ inventory_hostname }}"
        state: absent
